# Generated by Django 3.2.3 on 2021-06-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrou',
            fields=[
                ('n_identificacion', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=' Numero de Identificacion ')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='  Nombre Completo')),
                ('telefono', models.CharField(max_length=10, verbose_name=' Telefono ')),
                ('direccion', models.CharField(max_length=100, verbose_name=' Direccion ')),
                ('email', models.EmailField(max_length=150, verbose_name=' Email')),
                ('password', models.CharField(max_length=25, verbose_name=' Password ')),
                ('pais', models.CharField(max_length=50, verbose_name=' Pais')),
            ],
        ),
    ]
