# Generated by Django 3.2.3 on 2021-07-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registrou_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombrePais', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
    ]
